### ISSUE TITLE
Problems Running update_schema_for_card_file() to convert project cards

### ISSUE THREAD

**Issue by yueshuaing** [network-wrangler/projectcard#16]
I'm trying to run [update_schema_for_card_file() ](https://github.com/network-wrangler/projectcard/blob/main/projectcard/update.py#L424) to convert existing Metcouncil project cards to latest format. I'm having several issues:

**1. Invalid URI in [_load_schema()](https://github.com/network-wrangler/projectcard/blob/main/projectcard/validate.py#L64):** 

- Changing line 67 to `base_uri = f"file:///{base_path}/"` fixes the issue

**2. Can't convert the project cards which includes multiple changes**:
- For example, in [this project card](https://github.com/Metropolitan-Council/project_card_registry/blob/394_ml_reverse/projects/BaseMnPASS/394_Reverse_lane_onramp_MnPASS.yml), two roadway property changes are nested under `changes:`.
   - To resolve this, only one change should be kept, all others should be removed, and `changes:` should be removed and `facility` and `properties` should be the same level as `category`.

**3. Empty `tags`, `dependencies`:**
   - The `tags` and `dependencies` fields cannot be empty. They need to be either deleted or populated with some content.

**Comment by e-lo** [comment]
> The tags and dependencies fields cannot be empty. They need to be either deleted or populated with some content.

Is the issue that the conversion script outputs empty fields? Or that it doesn't work with empty fields?

**Comment by e-lo** [comment]
> To resolve this, only one change should be kept, all others should be removed, and changes: should be removed and facility and properties should be the same level as category.

Actually changes should still be there and you can have multiple project cards.  See[ schema](https://github.com/network-wrangler/projectcard/blob/main/schema/projectcard.json) .  I just realized I didn't add an example in this repo (I'll do that momentarily) but there are several in the network wrangler branch such as [this one](https://github.com/wsp-sag/network_wrangler/blob/selection-refactor/examples/stpaul/project_cards/road.add_delete.interchange.yml).

**Comment by e-lo** [comment]
> . Invalid URI in [_load_schema()](https://github.com/network-wrangler/projectcard/blob/main/projectcard/validate.py#L64):

I'm going to open a separate issue for this (in the future, please open individual issues so they can be addressed and closed individually)

**Comment by e-lo** [comment]
@yueshuaing - confirm this is fixed in in `v0.1.2` which is up on [PyPI](https://pypi.org/project/projectcard/)
